//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by resource.rc
//
#define IDI_TM                          101
#define IDC_OPTIONSTAB                  101
#define IDD_OPT                         102
#define IDI_OFFLINE                     102
#define IDD_INFO_QQ1                    103
#define IDD_INFO_QUN1                   105
#define IDD_INFO_QUN2                   106
#define IDD_INFO_QQ2                    108
#define IDD_INFO_QQ3                    109
#define IDD_ADDQUNMEMBER                111
#define IDD_OPT2                        112
#define IDD_CHANGESIGNATURE             115
#define IDD_QUNLIST                     116
#define IDR_QUNMEMBER                   117
#define IDD_OPTMAIN                     118
#define IDD_OPT_SETTINGS                119
#define IDD_SELECTIMAGE                 120
#define IDD_RENAMEIMAGE                 121
#define IDD_CODEVERIFY                  122
#define IDD_OPT3                        123
#define IDR_GIF1                        126
#define IDR_ERRORBMP                    126
#define IDD_ACCMGRUI                    127
#define IDD_CHOOSEACCOUNT               128
#define IDC_GROUPCONFIG                 1000
#define IDC_GROUPMAIN                   1002
#define IDC_INVISIBLE                   1004
#define IDC_NOADDIDENTITY               1009
#define IDC_REMOVENICKCHARS             1010
#define IDC_SUPPRESSQUN                 1011
#define IDC_WAITACK                     1011
#define IDC_REPLYMODEMSG                1012
#define IDC_CUSTOMBLOCK2                1013
#define IDC_SHOWAD                      1015
#define IDC_MAILNOTIFY                  1016
#define IDC_NOMODEMSG                   1017
#define IDC_NOREMOVEQUNIMAGE            1017
#define IDC_NOLOADQUNIMAGE              1018
#define IDC_NOPROGRESSPOPUPS            1018
#define IDC_ADDQUNNUMBER                1019
#define IDC_PASSWORD                    1020
#define IDC_NOSILENTQUNHISTORY          1020
#define IDC_LOGIN                       1022
#define IDC_INFO_CHANGEPWD              1052
#define IDC_INFO_CURRENTPWD             1053
#define IDC_INFO_NEWPWD                 1054
#define IDC_INFO_CONFIRMPWD             1055
#define IDC_INFO_ADDFREE                1056
#define IDC_INFO_ADDAUTH                1057
#define IDC_INFO_ADDNONE                1058
#define IDC_AVATARTYPE                  1059
#define IDC_QUNID                       1060
#define IDC_LEVEL                       1063
#define IDC_ONLINE                      1064
#define IDC_SIGNATURE                   1065
#define IDC_MEMBERLIST                  1066
#define IDC_STATUSASPERSONAL            1067
#define IDC_QUNNOTICE                   1068
#define IDC_QUNMEMBERS                  1069
#define IDC_CAPTION                     1070
#define IDC_IMAGELIST                   1072
#define IDC_ADD                         1073
#define IDC_NAME                        1074
#define IDC_REMOVE                      1074
#define IDC_SELECTFONT                  1077
#define IDC_SELECTCOLOR                 1078
#define IDC_UNICODEMSG                  1079
#define IDC_FORCEINVISIBLE              1080
#define IDC_AUTOSERVER                  1082
#define IDC_CHECK3                      1083
#define IDC_FORCEUNICODE                1083
#define IDC_CODE                        1085
#define IDC_CODEIMAGE                   1086
#define IDC_CONVERSION                  1087
#define IDC_NOTICE                      1088
#define IDC_BRIDGELIST                  1089
#define IDC_QUNLABEL                    1092
#define IDC_MEMBERLABEL                 1093
#define IDC_EDIT1                       1094
#define IDC_MANUALVERSION               1094
#define IDC_GLOBAL_WSPORT               1094
#define IDC_CURRENTVERSION              1095
#define IDC_GLOBAL_DISABLEQUN           1096
#define IDC_GLOBAL_WSDISABLE            1096
#define IDC_GLOBAL_WSNONLOCAL           1097
#define IDC_GLOBAL_WSROOT               1098
#define IDC_GLOBAL_WSBROWSE             1099
#define IDC_LIST1                       1101
#define IDC_QQLIST                      1101
#define IDC_SERVER                      1171
#define IDC_VERSION                     1202
#define IDC_INFO_IP                     1212
#define IDC_QUNINFO_QID                 1500
#define IDC_QUNINFO_NAME                1501
#define IDC_QUNINFO_CREATOR             1502
#define IDC_QUNINFO_MEMO                1503
#define IDC_QUNINFO_CATEGORY            1504
#define IDC_QUNINFO_NOTICE              1505
#define IDC_QUNINFO_DESC                1506
#define IDC_QUNINFO_MEMBERLIST          1507
#define IDC_QUNINFO_ADDTOME             1508
#define IDC_QUNINFO_DELMEMBER           1509
#define IDC_QUNINFO_SETADMIN            1510
#define IDC_QUNINFO_UNSETADMIN          1511
#define IDC_QUNINFO_TRANSFER            1512
#define IDC_QUNINFO_GENDER              1513
#define IDC_QUNINFO_REALNAME            1514
#define IDC_QUNINFO_TELEPHONE           1515
#define IDC_QUNINFO_EMAIL               1516
#define IDC_INFO_SEX                    1600
#define IDC_INFO_AREA                   1601
#define IDC_INFO_PROVINCE               1602
#define IDC_INFO_CITY                   1603
#define IDC_INFO_FACE                   1604
#define IDC_INFO_QQSHOW                 1605
#define IDC_INFO_ANYONE                 1606
#define IDC_INFO_NOONE                  1607
#define IDC_INFO_FRDONLY                1608
#define IDC_INFO_EMAIL                  1609
#define IDC_INFO_ADDRESS                1610
#define IDC_INFO_ZIPCODE                1611
#define IDC_INFO_PHONE                  1612
#define IDC_INFO_MOBILE                 1613
#define IDC_INFO_REALNAME               1614
#define IDC_INFO_COLLEGE                1615
#define IDC_INFO_OCCUPATION             1616
#define IDC_INFO_ANIMAL                 1617
#define IDC_INFO_BLOOD                  1618
#define IDC_INFO_HOROSCOPE              1619
#define IDC_INFO_UID                    1620
#define IDC_INFO_NICKNAME               1621
#define IDC_INFO_CLIENTVER              1622
#define IDC_INFO_AGE                    1623
#define IDC_INFO_HOMEPAGE               1624
#define IDC_INFO_DESCRIPTION            1625
#define IDC_INFO_SIGNATURE              1626
#define ID__SENDMESSAGE                 40001
#define ID__USERDETAILS                 40002
#define ID__KICKMEMBER                  40003
#define ID__INFO                        40005
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        129
#define _APS_NEXT_COMMAND_VALUE         40006
#define _APS_NEXT_CONTROL_VALUE         1102
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
